version: '3.7'
services:
  user-database:
    image: "postgres"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"  
volumes:
  database-data: # named volumes can be managed easier using docker-compose
